import getpass
import json
import os
from datetime import datetime
from pathlib import Path


STAMP_TITLE = "MITSU FILE PROVENANCE"

LINE_COMMENT_EXTS = {
    ".py", ".sh", ".bash", ".zsh", ".js", ".jsx", ".ts", ".tsx", ".java",
    ".c", ".h", ".cpp", ".hpp", ".cs", ".go", ".rs", ".rb", ".php", ".swift",
    ".kt", ".kts", ".lua", ".r", ".sql", ".yaml", ".yml", ".toml", ".ini",
    ".cfg", ".conf", ".ps1", ".dockerfile", ".gitignore",
}
HTML_COMMENT_EXTS = {".html", ".htm", ".xml", ".svg"}
CSS_COMMENT_EXTS = {".css", ".scss", ".sass", ".less"}
PLAIN_TEXT_EXTS = {".txt", ".md", ".rst", ".log", ".text"}
EMBEDDABLE_EXTS = LINE_COMMENT_EXTS | HTML_COMMENT_EXTS | CSS_COMMENT_EXTS | PLAIN_TEXT_EXTS


def generated_by() -> str:
    user = os.environ.get("MITSU_USER") or getpass.getuser()
    return f"MITSU for {user}"


def _timestamp() -> str:
    return datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")


def _context(context: str) -> str:
    text = " ".join(str(context or "Generated by MITSU.").split())
    return text[:700]


def _metadata(target: Path, context: str) -> dict:
    return {
        "title": STAMP_TITLE,
        "generated_by": generated_by(),
        "created_at": _timestamp(),
        "file": target.name,
        "context": _context(context),
    }


def _has_stamp(content: str) -> bool:
    return content.lstrip().startswith(STAMP_TITLE) or STAMP_TITLE in content[:600]


def _comment_lines(lines: list[str], marker: str) -> str:
    return "\n".join(f"{marker} {line}".rstrip() for line in lines) + "\n\n"


def stamp_text_content(content: str, target: Path, context: str) -> str:
    text = str(content or "")
    if _has_stamp(text):
        return text

    meta = _metadata(target, context)
    lines = [
        STAMP_TITLE,
        f"Generated by: {meta['generated_by']}",
        f"Date: {meta['created_at']}",
        f"File context: {meta['context']}",
    ]
    ext = target.suffix.lower()

    if target.name.lower() == "dockerfile" or ext in LINE_COMMENT_EXTS:
        header = _comment_lines(lines, "#")
    elif ext in HTML_COMMENT_EXTS:
        header = "<!--\n" + "\n".join(lines) + "\n-->\n\n"
    elif ext in CSS_COMMENT_EXTS:
        header = "/*\n" + "\n".join(lines) + "\n*/\n\n"
    else:
        header = "\n".join(lines) + "\n\n"

    return header + text


def can_embed_stamp(target: Path) -> bool:
    return target.suffix.lower() in EMBEDDABLE_EXTS or target.name.lower() == "dockerfile"


def write_text_with_stamp(
    target: Path,
    content: str,
    context: str,
    encoding: str = "utf-8",
) -> None:
    if can_embed_stamp(target):
        target.write_text(stamp_text_content(content, target, context), encoding=encoding)
        return
    target.write_text(str(content or ""), encoding=encoding)
    write_sidecar_metadata(target, context)


def write_sidecar_metadata(target: Path, context: str) -> Path:
    sidecar = target.with_name(f"{target.name}.mitsu_meta.json")
    sidecar.write_text(
        json.dumps(_metadata(target, context), indent=2),
        encoding="utf-8",
    )
    return sidecar


def mark_created_file(target: Path, context: str) -> None:
    if not target.exists() or target.is_dir():
        return
    if can_embed_stamp(target):
        try:
            content = target.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            write_sidecar_metadata(target, context)
            return
        write_text_with_stamp(target, content, context)
        return
    write_sidecar_metadata(target, context)
