"""Mitsu — Multi-language support system."""
from pathlib import Path


LANGUAGES = {
    "en": {"name": "English", "native": "English"},
    "hi": {"name": "Hindi", "native": "हिन्दी"},
    "ja": {"name": "Japanese", "native": "日本語"},
    "es": {"name": "Spanish", "native": "Español"},
    "fr": {"name": "French", "native": "Français"},
    "de": {"name": "German", "native": "Deutsch"},
    "pt": {"name": "Portuguese", "native": "Português"},
    "ko": {"name": "Korean", "native": "한국어"},
    "zh": {"name": "Chinese", "native": "中文"},
    "ar": {"name": "Arabic", "native": "العربية"},
    "ru": {"name": "Russian", "native": "Русский"},
    "it": {"name": "Italian", "native": "Italiano"},
    "th": {"name": "Thai", "native": "ไทย"},
    "tr": {"name": "Turkish", "native": "Türkçe"},
    "vi": {"name": "Vietnamese", "native": "Tiếng Việt"},
    "bn": {"name": "Bengali", "native": "বাংলা"},
    "ta": {"name": "Tamil", "native": "தமிழ்"},
    "te": {"name": "Telugu", "native": "తెలుగు"},
    "mar": {"name": "Marathi", "native": "मराठी"},
    "gu": {"name": "Gujarati", "native": "ગુજરાતી"},
    "kn": {"name": "Kannada", "native": "ಕನ್ನಡ"},
    "ml": {"name": "Malayalam", "native": "മലയാളം"},
    "pa": {"name": "Punjabi", "native": "ਪੰਜਾਬੀ"},
    "ur": {"name": "Urdu", "native": "اردو"},
    "sw": {"name": "Swahili", "native": "Kiswahili"},
    "nl": {"name": "Dutch", "native": "Nederlands"},
    "pl": {"name": "Polish", "native": "Polski"},
    "sv": {"name": "Swedish", "native": "Svenska"},
    "id": {"name": "Indonesian", "native": "Bahasa Indonesia"},
    "ms": {"name": "Malay", "native": "Bahasa Melayu"},
}


STRINGS = {
    "en": {
        "welcome": "Welcome to M I T S U",
        "setup_subtitle": "Let's get you set up!",
        "name_prompt": "What should I call you?",
        "name_hint": "Enter your name",
        "voice_prompt": "Choose a voice for Mitsu:",
        "start_button": "Start Chatting",
        "language_prompt": "Choose your language:",
        "input_hint": "Type a message...",
        "settings": "Settings",
        "mood": "Mood",
        "theme": "Theme",
        "listening": "Listening...",
        "thinking": "Thinking...",
        "speaking": "Speaking...",
        "error": "Something went wrong",
        "good_morning": "Good morning",
        "good_afternoon": "Good afternoon",
        "good_evening": "Good evening",
        "good_night": "Good night",
        "hey": "Hey",
    },
    "hi": {
        "welcome": "M I T S U में आपका स्वागत है",
        "setup_subtitle": "चलिए सेटअप करते हैं!",
        "name_prompt": "मैं आपको क्या बुलाऊँ?",
        "name_hint": "अपना नाम दर्ज करें",
        "voice_prompt": "Mitsu के लिए आवाज़ चुनें:",
        "start_button": "चैट शुरू करें",
        "language_prompt": "अपनी भाषा चुनें:",
        "input_hint": "संदेश टाइप करें...",
        "settings": "सेटिंग्स",
        "mood": "मूड",
        "theme": "थीम",
        "listening": "सुन रहा हूँ...",
        "thinking": "सोच रहा हूँ...",
        "speaking": "बोल रहा हूँ...",
        "error": "कुछ गलत हो गया",
        "good_morning": "सुप्रभात",
        "good_afternoon": "शुभ अपराह्न",
        "good_evening": "शुभ संध्या",
        "good_night": "शुभ रात्रि",
        "hey": "अरे",
    },
    "ja": {
        "welcome": "M I T S U へようこそ",
        "setup_subtitle": "セットアップを始めましょう！",
        "name_prompt": "名前を教えてください",
        "name_hint": "名前を入力",
        "voice_prompt": "音声を選んでください：",
        "start_button": "チャット開始",
        "language_prompt": "言語を選んでください：",
        "input_hint": "メッセージを入力...",
        "settings": "設定",
        "mood": "気分",
        "theme": "テーマ",
        "listening": "聞いています...",
        "thinking": "考え中...",
        "speaking": "話しています...",
        "error": "エラーが発生しました",
        "good_morning": "おはようございます",
        "good_afternoon": "こんにちは",
        "good_evening": "こんばんは",
        "good_night": "おやすみなさい",
        "hey": "やあ",
    },
    "es": {
        "welcome": "Bienvenido a M I T S U",
        "setup_subtitle": "¡Vamos a configurarte!",
        "name_prompt": "¿Cómo te llamo?",
        "name_hint": "Ingresa tu nombre",
        "voice_prompt": "Elige una voz para Mitsu:",
        "start_button": "Empezar a Chatear",
        "language_prompt": "Elige tu idioma:",
        "input_hint": "Escribe un mensaje...",
        "settings": "Ajustes",
        "mood": "Ánimo",
        "theme": "Tema",
        "listening": "Escuchando...",
        "thinking": "Pensando...",
        "speaking": "Hablando...",
        "error": "Algo salió mal",
        "good_morning": "Buenos días",
        "good_afternoon": "Buenas tardes",
        "good_evening": "Buenas noches",
        "good_night": "Buenas noches",
        "hey": "Hola",
    },
    "fr": {
        "welcome": "Bienvenue sur M I T S U",
        "setup_subtitle": "Configurons votre assistant !",
        "name_prompt": "Comment vous appeler ?",
        "name_hint": "Entrez votre nom",
        "voice_prompt": "Choisissez une voix pour Mitsu :",
        "start_button": "Commencer à Discuter",
        "language_prompt": "Choisissez votre langue :",
        "input_hint": "Tapez un message...",
        "settings": "Paramètres",
        "mood": "Humeur",
        "theme": "Thème",
        "listening": "Écoute...",
        "thinking": "Réflexion...",
        "speaking": "Parle...",
        "error": "Une erreur s'est produite",
        "good_morning": "Bonjour",
        "good_afternoon": "Bon après-midi",
        "good_evening": "Bonsoir",
        "good_night": "Bonne nuit",
        "hey": "Salut",
    },
    "de": {
        "welcome": "Willkommen bei M I T S U",
        "setup_subtitle": "Lass uns einrichten!",
        "name_prompt": "Wie soll ich dich nennen?",
        "name_hint": "Gib deinen Namen ein",
        "voice_prompt": "Wähle eine Stimme für Mitsu:",
        "start_button": "Chat starten",
        "language_prompt": "Wähle deine Sprache:",
        "input_hint": "Nachricht eingeben...",
        "settings": "Einstellungen",
        "mood": "Stimmung",
        "theme": "Thema",
        "listening": "Höre zu...",
        "thinking": "Denke nach...",
        "speaking": "Spreche...",
        "error": "Etwas ist schiefgelaufen",
        "good_morning": "Guten Morgen",
        "good_afternoon": "Guten Tag",
        "good_evening": "Guten Abend",
        "good_night": "Gute Nacht",
        "hey": "Hey",
    },
    "ko": {
        "welcome": "M I T S U 에 오신 것을 환영합니다",
        "setup_subtitle": "설정을 시작합시다!",
        "name_prompt": "이름이 뭐예요?",
        "name_hint": "이름을 입력하세요",
        "voice_prompt": "음성을 선택하세요:",
        "start_button": "채팅 시작",
        "language_prompt": "언어를 선택하세요:",
        "input_hint": "메시지를 입력하세요...",
        "settings": "설정",
        "mood": "기분",
        "theme": "테마",
        "listening": "듣는 중...",
        "thinking": "생각 중...",
        "speaking": "말하는 중...",
        "error": "문제가 발생했습니다",
        "good_morning": "좋은 아침",
        "good_afternoon": "좋은 오후",
        "good_evening": "좋은 저녁",
        "good_night": "잘 자요",
        "hey": "안녕",
    },
    "zh": {
        "welcome": "欢迎使用 M I T S U",
        "setup_subtitle": "让我们开始设置吧！",
        "name_prompt": "我该怎么称呼你？",
        "name_hint": "输入你的名字",
        "voice_prompt": "为Mitsu选择一个声音：",
        "start_button": "开始聊天",
        "language_prompt": "选择你的语言：",
        "input_hint": "输入消息...",
        "settings": "设置",
        "mood": "心情",
        "theme": "主题",
        "listening": "正在听...",
        "thinking": "思考中...",
        "speaking": "正在说...",
        "error": "出了点问题",
        "good_morning": "早上好",
        "good_afternoon": "下午好",
        "good_evening": "晚上好",
        "good_night": "晚安",
        "hey": "嘿",
    },
    "ar": {
        "welcome": "مرحبًا بك في M I T S U",
        "setup_subtitle": "دعنا نبدأ الإعداد!",
        "name_prompt": "كيف يجب أن أناديك؟",
        "name_hint": "أدخل اسمك",
        "voice_prompt": "اختر صوتًا لـ Mitsu:",
        "start_button": "ابدأ المحادثة",
        "language_prompt": "اختر لغتك:",
        "input_hint": "اكتب رسالة...",
        "settings": "الإعدادات",
        "mood": "المزاج",
        "theme": "السمة",
        "listening": "أستمع...",
        "thinking": "أفكر...",
        "speaking": "أتحدث...",
        "error": "حدث خطأ ما",
        "good_morning": "صباح الخير",
        "good_afternoon": "مساء الخير",
        "good_evening": "مساء الخير",
        "good_night": "تصبح على خير",
        "hey": "مرحبًا",
    },
    "ru": {
        "welcome": "Добро пожаловать в M I T S U",
        "setup_subtitle": "Давайте настроим!",
        "name_prompt": "Как вас называть?",
        "name_hint": "Введите ваше имя",
        "voice_prompt": "Выберите голос для Mitsu:",
        "start_button": "Начать Чат",
        "language_prompt": "Выберите язык:",
        "input_hint": "Введите сообщение...",
        "settings": "Настройки",
        "mood": "Настроение",
        "theme": "Тема",
        "listening": "Слушаю...",
        "thinking": "Думаю...",
        "speaking": "Говорю...",
        "error": "Что-то пошло не так",
        "good_morning": "Доброе утро",
        "good_afternoon": "Добрый день",
        "good_evening": "Добрый вечер",
        "good_night": "Спокойной ночи",
        "hey": "Привет",
    },
    "pt": {
        "welcome": "Bem-vindo ao M I T S U",
        "setup_subtitle": "Vamos configurar!",
        "name_prompt": "Como devo te chamar?",
        "name_hint": "Digite seu nome",
        "voice_prompt": "Escolha uma voz para o Mitsu:",
        "start_button": "Começar a Conversar",
        "language_prompt": "Escolha seu idioma:",
        "input_hint": "Digite uma mensagem...",
        "settings": "Configurações",
        "mood": "Humor",
        "theme": "Tema",
        "listening": "Ouvindo...",
        "thinking": "Pensando...",
        "speaking": "Falando...",
        "error": "Algo deu errado",
        "good_morning": "Bom dia",
        "good_afternoon": "Boa tarde",
        "good_evening": "Boa noite",
        "good_night": "Boa noite",
        "hey": "Oi",
    },
    "it": {
        "welcome": "Benvenuto su M I T S U",
        "setup_subtitle": "Configuriamo!",
        "name_prompt": "Come dovrei chiamarti?",
        "name_hint": "Inserisci il tuo nome",
        "voice_prompt": "Scegli una voce per Mitsu:",
        "start_button": "Inizia a Chatting",
        "language_prompt": "Scegli la tua lingua:",
        "input_hint": "Scrivi un messaggio...",
        "settings": "Impostazioni",
        "mood": "Umore",
        "theme": "Tema",
        "listening": "Ascolto...",
        "thinking": "Pensando...",
        "speaking": "Parlo...",
        "error": "Qualcosa è andato storto",
        "good_morning": "Buongiorno",
        "good_afternoon": "Buon pomeriggio",
        "good_evening": "Buonasera",
        "good_night": "Buonanotte",
        "hey": "Ciao",
    },
    "tr": {
        "welcome": "M I T S U'ya Hoş Geldiniz",
        "setup_subtitle": "Hadi ayarlayalım!",
        "name_prompt": "Sana ne diyeyim?",
        "name_hint": "Adını gir",
        "voice_prompt": "Mitsu için bir ses seç:",
        "start_button": "Sohbete Başla",
        "language_prompt": "Dilini seç:",
        "input_hint": "Mesaj yaz...",
        "settings": "Ayarlar",
        "mood": "Ruh Hali",
        "theme": "Tema",
        "listening": "Dinliyor...",
        "thinking": "Düşünüyor...",
        "speaking": "Konuşuyor...",
        "error": "Bir şeyler yanlış gitti",
        "good_morning": "Günaydın",
        "good_afternoon": "İyi günler",
        "good_evening": "İyi akşamlar",
        "good_night": "İyi geceler",
        "hey": "Selam",
    },
    "th": {
        "welcome": "ยินดีต้อนรับสู่ M I T S U",
        "setup_subtitle": "มาตั้งค่ากันเถอะ!",
        "name_prompt": "ควรเรียกคุณว่าอะไร?",
        "name_hint": "ป้อนชื่อของคุณ",
        "voice_prompt": "เลือกเสียงสำหรับ Mitsu:",
        "start_button": "เริ่มแชท",
        "language_prompt": "เลือกภาษาของคุณ:",
        "input_hint": "พิมพ์ข้อความ...",
        "settings": "ตั้งค่า",
        "mood": "อารมณ์",
        "theme": "ธีม",
        "listening": "กำลังฟัง...",
        "thinking": "กำลังคิด...",
        "speaking": "กำลังพูด...",
        "error": "เกิดข้อผิดพลาด",
        "good_morning": "สวัสดีตอนเช้า",
        "good_afternoon": "สวัสดีตอนบ่าย",
        "good_evening": "สวัสดีตอนเย็น",
        "good_night": "ราตรีสวัสดิ์",
        "hey": "สวัสดี",
    },
    "vi": {
        "welcome": "Chào mừng đến với M I T S U",
        "setup_subtitle": "Hãy thiết lập!",
        "name_prompt": "Tôi nên gọi bạn là gì?",
        "name_hint": "Nhập tên của bạn",
        "voice_prompt": "Chọn giọng nói cho Mitsu:",
        "start_button": "Bắt đầu Chat",
        "language_prompt": "Chọn ngôn ngữ:",
        "input_hint": "Nhập tin nhắn...",
        "settings": "Cài đặt",
        "mood": "Tâm trạng",
        "theme": "Chủ đề",
        "listening": "Đang nghe...",
        "thinking": "Đang suy nghĩ...",
        "speaking": "Đang nói...",
        "error": "Đã xảy ra lỗi",
        "good_morning": "Chào buổi sáng",
        "good_afternoon": "Chào buổi chiều",
        "good_evening": "Chào buổi tối",
        "good_night": "Chúc ngủ ngon",
        "hey": "Xin chào",
    },
    "bn": {
        "welcome": "M I T S U তে স্বাগতম",
        "setup_subtitle": "সেটআপ করা যাক!",
        "name_prompt": "আমি আপনাকে কী বলব?",
        "name_hint": "আপনার নাম লিখুন",
        "voice_prompt": "Mitsu এর জন্য একটি কণ্ঠ বাছাই করুন:",
        "start_button": "চ্যাট শুরু করুন",
        "language_prompt": "আপনার ভাষা বাছাই করুন:",
        "input_hint": "একটি বার্তা লিখুন...",
        "settings": "সেটিংস",
        "mood": "মেজাজ",
        "theme": "থিম",
        "listening": "শুনছি...",
        "thinking": "ভাবছি...",
        "speaking": "বলছি...",
        "error": "কিছু ভুল হয়েছে",
        "good_morning": "সুপ্রভাত",
        "good_afternoon": "শুভ অপরাহ্ন",
        "good_evening": "শুভ সন্ধ্যা",
        "good_night": "শুভ রাত্রি",
        "hey": "হ্যালো",
    },
    "ta": {
        "welcome": "M I T S U க்கு வரவேற்கிறோம்",
        "setup_subtitle": "அமைப்பைத் தொடங்குவோம்!",
        "name_prompt": "நான் உங்களை என்ன அழைக்க வேண்டும்?",
        "name_hint": "உங்கள் பெயரை உள்ளிடவும்",
        "voice_prompt": "Mitsu க்கு ஒரு குரலைத் தேர்ந்தெடுக்கவும்:",
        "start_button": "உரையாடலைத் தொடங்கு",
        "language_prompt": "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்:",
        "input_hint": "ஒரு செய்தியை உள்ளிடவும்...",
        "settings": "அமைப்புகள்",
        "mood": "மனநிலை",
        "theme": "தீம்",
        "listening": "கேட்கிறது...",
        "thinking": "யோசிக்கிறது...",
        "speaking": "பேசுகிறது...",
        "error": "ஏதோ தவறு நடந்தது",
        "good_morning": "காலை வணக்கம்",
        "good_afternoon": "மதிய வணக்கம்",
        "good_evening": "மாலை வணக்கம்",
        "good_night": "இனிய இரவு",
        "hey": "வணக்கம்",
    },
    "te": {
        "welcome": "M I T S U కు స్వాగతం",
        "setup_subtitle": "సెటప్ చేద్దాం!",
        "name_prompt": "నేను మిమ్మల్ని ఏమి పిలవాలి?",
        "name_hint": "మీ పేరు నమోదు చేయండి",
        "voice_prompt": "Mitsu కోసం ఒక గొంతు ఎంచుకోండి:",
        "start_button": "చాట్ ప్రారంభించండి",
        "language_prompt": "మీ భాష ఎంచుకోండి:",
        "input_hint": "సందేశం టైప్ చేయండి...",
        "settings": "సెట్టింగ్‌లు",
        "mood": "మూడ్",
        "theme": "థీమ్",
        "listening": "వింటోంది...",
        "thinking": "ఆలోచిస్తోంది...",
        "speaking": "మాట్లాడుతోంది...",
        "error": "ఏదో తప్పు జరిగింది",
        "good_morning": "శుభోదయం",
        "good_afternoon": "శుభ మధ్యాహ్నం",
        "good_evening": "శుభ సాయంత్రం",
        "good_night": "శుభ రాత్రి",
        "hey": "హాయ్",
    },
    "mar": {
        "welcome": "M I T S U मध्ये आपले स्वागत आहे",
        "setup_subtitle": "सेटअप करूया!",
        "name_prompt": "मी तुम्हाला काय म्हणू?",
        "name_hint": "तुमचे नाव प्रविष्ट करा",
        "voice_prompt": "Mitsu साठी आवाज निवडा:",
        "start_button": "चॅट सुरू करा",
        "language_prompt": "तुमची भाषा निवडा:",
        "input_hint": "संदेश टाइप करा...",
        "settings": "सेटिंग्ज",
        "mood": "मूड",
        "theme": "थीम",
        "listening": "ऐकत आहे...",
        "thinking": "विचार करत आहे...",
        "speaking": "बोलत आहे...",
        "error": "काहीतरी चूक झाली",
        "good_morning": "सुप्रभात",
        "good_afternoon": "शुभ दुपारी",
        "good_evening": "शुभ संध्या",
        "good_night": "शुभ रात्री",
        "hey": "अरे",
    },
    "gu": {
        "welcome": "M I T S U માં આપનું સ્વાગત છે",
        "setup_subtitle": "સેટઅપ કરીએ!",
        "name_prompt": "હું તમને શું બોલાવું?",
        "name_hint": "તમારું નામ દાખલ કરો",
        "voice_prompt": "Mitsu માટે અવાજ પસંદ કરો:",
        "start_button": "ચેટ શરૂ કરો",
        "language_prompt": "તમારી ભાષા પસંદ કરો:",
        "input_hint": "સંદેશ ટાઇપ કરો...",
        "settings": "સેટિંગ્સ",
        "mood": "મૂડ",
        "theme": "થીમ",
        "listening": "સાંભળી રહ્યા છીએ...",
        "thinking": "વિચારી રહ્યા છીએ...",
        "speaking": "બોલી રહ્યા છીએ...",
        "error": "કંઈક ખોટું થયું",
        "good_morning": "સુપ્રભાત",
        "good_afternoon": "શુભ બપોરે",
        "good_evening": "શુભ સાંજે",
        "good_night": "શુભ રાત્રી",
        "hey": "હેલો",
    },
    "kn": {
        "welcome": "M I T S U ಗೆ ಸ್ವಾಗತ",
        "setup_subtitle": "ಸೆಟಪ್ ಮಾಡೋಣ!",
        "name_prompt": "ನಾನು ನಿಮ್ಮನ್ನು ಏನು ಕರೆಯಬೇಕು?",
        "name_hint": "ನಿಮ್ಮ ಹೆಸರು ನಮೂದಿಸಿ",
        "voice_prompt": "Mitsu ಗಾಗಿ ಧ್ವನಿ ಆಯ್ಕೆಮಾಡಿ:",
        "start_button": "ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ",
        "language_prompt": "ನಿಮ್ಮ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ:",
        "input_hint": "ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...",
        "settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "mood": "ಮೂಡ್",
        "theme": "ಥೀಮ್",
        "listening": "ಕೇಳುತ್ತಿದೆ...",
        "thinking": "ಯೋಚಿಸುತ್ತಿದೆ...",
        "speaking": "ಮಾತನಾಡುತ್ತಿದೆ...",
        "error": "ಏನೋ ತಪ್ಪಾಗಿದೆ",
        "good_morning": "ಶುಭೋದಯ",
        "good_afternoon": "ಶುಭ ಮಧ್ಯಾಹ್ನ",
        "good_evening": "ಶುಭ ಸಂಜೆ",
        "good_night": "ಶುಭ ರಾತ್ರಿ",
        "hey": "ಹಾಯ್",
    },
    "ml": {
        "welcome": "M I T S U ലേക്ക് സ്വാഗതം",
        "setup_subtitle": "സെറ്റപ്പ് ചെയ്യാം!",
        "name_prompt": "ഞാൻ നിങ്ങളെ എന്ത് വിളിക്കണം?",
        "name_hint": "നിങ്ങളുടെ പേര് നൽകുക",
        "voice_prompt": "Mitsu ന് ഒരു ശബ്ദം തിരഞ്ഞെടുക്കുക:",
        "start_button": "ചാറ്റ് ആരംഭിക്കുക",
        "language_prompt": "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക:",
        "input_hint": "ഒരു സന്ദേശം ടൈപ്പ് ചെയ്യുക...",
        "settings": "ക്രമീകരണങ്ങൾ",
        "mood": "മൂഡ്",
        "theme": "തീം",
        "listening": "കേൾക്കുന്നു...",
        "thinking": "ചിന്തിക്കുന്നു...",
        "speaking": "സംസാരിക്കുന്നു...",
        "error": "എന്തോ തെറ്റ് സംഭവിച്ചു",
        "good_morning": "സുപ്രഭാതം",
        "good_afternoon": "ശുഭ ഉച്ച",
        "good_evening": "ശുഭ വൈകുന്നേരം",
        "good_night": "ശുഭ രാത്രി",
        "hey": "ഹായ്",
    },
    "pa": {
        "welcome": "M I T S U ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
        "setup_subtitle": "ਸੈਟਅਪ ਕਰੀਏ!",
        "name_prompt": "ਮੈਂ ਤੁਹਾਡਾ ਕੀ ਕਹਾਂ?",
        "name_hint": "ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ",
        "voice_prompt": "Mitsu ਲਈ ਅਵਾਜ਼ ਚੁਣੋ:",
        "start_button": "ਚੈਟ ਸ਼ੁਰੂ ਕਰੋ",
        "language_prompt": "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ:",
        "input_hint": "ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...",
        "settings": "ਸੈਟਿੰਗਾਂ",
        "mood": "ਮੂਡ",
        "theme": "ਥੀਮ",
        "listening": "ਸੁਣ ਰਿਹਾ ਹੈ...",
        "thinking": "ਸੋਚ ਰਿਹਾ ਹੈ...",
        "speaking": "ਬੋਲ ਰਿਹਾ ਹੈ...",
        "error": "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ",
        "good_morning": "ਸ਼ੁਭ ਸਵੇਰ",
        "good_afternoon": "ਸ਼ੁਭ ਦੁਪਹਿਰ",
        "good_evening": "ਸ਼ੁਭ ਸ਼ਾਮ",
        "good_night": "ਸ਼ੁਭ ਰਾਤ",
        "hey": "ਹੈਲੋ",
    },
    "ur": {
        "welcome": "M I T S U میں خوش آمدید",
        "setup_subtitle": "سیٹ اپ کرتے ہیں!",
        "name_prompt": "میں آپ کو کیا بلاؤں؟",
        "name_hint": "اپنا نام درج کریں",
        "voice_prompt": "Mitsu کے لیے آواز منتخب کریں:",
        "start_button": "چیٹ شروع کریں",
        "language_prompt": "اپنی زبان منتخب کریں:",
        "input_hint": "پیغام ٹائپ کریں...",
        "settings": "ترتیبات",
        "mood": "مود",
        "theme": "تھیم",
        "listening": "سن رہا ہے...",
        "thinking": "سوچ رہا ہے...",
        "speaking": "بول رہا ہے...",
        "error": "کچھ غلط ہو گیا",
        "good_morning": "صبح بخیر",
        "good_afternoon": "دوپہر بخیر",
        "good_evening": "شام بخیر",
        "good_night": "شب بخیر",
        "hey": "ہیلو",
    },
    "sw": {
        "welcome": "Karibu kwenye M I T S U",
        "setup_subtitle": "Tuweke injini!",
        "name_prompt": "Nitakuita nini?",
        "name_hint": "Weka jina lako",
        "voice_prompt": "Chagua sauti kwa Mitsu:",
        "start_button": "Anza Kuzungumza",
        "language_prompt": "Chagua lugha yako:",
        "input_hint": "Andika ujumbe...",
        "settings": "Mipangilio",
        "mood": "Hali",
        "theme": "Mandhari",
        "listening": "Ninasikiliza...",
        "thinking": "Ninafikiria...",
        "speaking": "Ninazungumza...",
        "error": "Kuna kitu kimeenda vibaya",
        "good_morning": "Habari za asubuhi",
        "good_afternoon": "Habari za mchana",
        "good_evening": "Habari za jioni",
        "good_night": "Usiku mwema",
        "hey": "Habari",
    },
    "nl": {
        "welcome": "Welkom bij M I T S U",
        "setup_subtitle": "Laten we instellen!",
        "name_prompt": "Hoe zal ik je noemen?",
        "name_hint": "Voer je naam in",
        "voice_prompt": "Kies een stem voor Mitsu:",
        "start_button": "Begin met Chatten",
        "language_prompt": "Kies je taal:",
        "input_hint": "Typ een bericht...",
        "settings": "Instellingen",
        "mood": "Stemming",
        "theme": "Thema",
        "listening": "Luistert...",
        "thinking": "Denkt na...",
        "speaking": "Spreekt...",
        "error": "Er is iets misgegaan",
        "good_morning": "Goedemorgen",
        "good_afternoon": "Goedemiddag",
        "good_evening": "Goedenavond",
        "good_night": "Goedenacht",
        "hey": "Hoi",
    },
    "pl": {
        "welcome": "Witaj w M I T S U",
        "setup_subtitle": "Skonfigurujmy!",
        "name_prompt": "Jak mam cię nazywać?",
        "name_hint": "Wpisz swoje imię",
        "voice_prompt": "Wybierz głos dla Mitsu:",
        "start_button": "Rozpocznij Czat",
        "language_prompt": "Wybierz język:",
        "input_hint": "Wpisz wiadomość...",
        "settings": "Ustawienia",
        "mood": "Nastrój",
        "theme": "Motyw",
        "listening": "Słucha...",
        "thinking": "Myśli...",
        "speaking": "Mówi...",
        "error": "Coś poszło nie tak",
        "good_morning": "Dzień dobry",
        "good_afternoon": "Dzień dobry",
        "good_evening": "Dobry wieczór",
        "good_night": "Dobranoc",
        "hey": "Cześć",
    },
    "sv": {
        "welcome": "Välkommen till M I T S U",
        "setup_subtitle": "Låt oss ställa in!",
        "name_prompt": "Vad ska jag kalla dig?",
        "name_hint": "Ange ditt namn",
        "voice_prompt": "Välj en röst för Mitsu:",
        "start_button": "Börja Chatta",
        "language_prompt": "Välj ditt språk:",
        "input_hint": "Skriv ett meddelande...",
        "settings": "Inställningar",
        "mood": "Humör",
        "theme": "Tema",
        "listening": "Lyssnar...",
        "thinking": "Tänker...",
        "speaking": "Talar...",
        "error": "Något gick fel",
        "good_morning": "God morgon",
        "good_afternoon": "God eftermiddag",
        "good_evening": "God kväll",
        "good_night": "God natt",
        "hey": "Hej",
    },
    "id": {
        "welcome": "Selamat datang di M I T S U",
        "setup_subtitle": "Ayo mulai!",
        "name_prompt": "Apa yang harus saya panggil Anda?",
        "name_hint": "Masukkan nama Anda",
        "voice_prompt": "Pilih suara untuk Mitsu:",
        "start_button": "Mulai Mengobrol",
        "language_prompt": "Pilih bahasa Anda:",
        "input_hint": "Ketik pesan...",
        "settings": "Pengaturan",
        "mood": "Suasana",
        "theme": "Tema",
        "listening": "Mendengarkan...",
        "thinking": "Berpikir...",
        "speaking": "Berbicara...",
        "error": "Terjadi kesalahan",
        "good_morning": "Selamat pagi",
        "good_afternoon": "Selamat siang",
        "good_evening": "Selamat malam",
        "good_night": "Selamat tidur",
        "hey": "Halo",
    },
    "ms": {
        "welcome": "Selamat datang ke M I T S U",
        "setup_subtitle": "Mari mula!",
        "name_prompt": "Apa yang patut saya panggil anda?",
        "name_hint": "Masukkan nama anda",
        "voice_prompt": "Pilih suara untuk Mitsu:",
        "start_button": "Mula Berbual",
        "language_prompt": "Pilih bahasa anda:",
        "input_hint": "Taip mesej...",
        "settings": "Tetapan",
        "mood": "Suasana",
        "theme": "Tema",
        "listening": "Mendengar...",
        "thinking": "Berpikir...",
        "speaking": "Bercakap...",
        "error": "Sesuatu telah berlaku",
        "good_morning": "Selamat pagi",
        "good_afternoon": "Selamat tengah hari",
        "good_evening": "Selamat petang",
        "good_night": "Selamat malam",
        "hey": "Hai",
    },
}


class LangManager:
    def __init__(self):
        self.current_lang = "en"
        self._load()

    def _lang_file(self):
        return Path.home() / ".mitsu" / "language.txt"

    def _load(self):
        try:
            f = self._lang_file()
            if f.exists():
                lang = f.read_text().strip()
                if lang in LANGUAGES:
                    self.current_lang = lang
        except Exception:
            pass

    def set_language(self, lang_code):
        if lang_code in LANGUAGES:
            self.current_lang = lang_code
            try:
                f = self._lang_file()
                f.parent.mkdir(parents=True, exist_ok=True)
                f.write_text(lang_code)
            except Exception:
                pass

    def t(self, key):
        lang_dict = STRINGS.get(self.current_lang, STRINGS["en"])
        return lang_dict.get(key, STRINGS["en"].get(key, key))

    def get_lang_name(self, code=None):
        if code is None:
            code = self.current_lang
        return LANGUAGES.get(code, {}).get("native", code)

    def get_lang_list(self):
        return [(code, info["native"]) for code, info in LANGUAGES.items()]

    def get_lang_context(self):
        lang_name = self.get_lang_name()
        return f"The user speaks {lang_name}. Respond in {lang_name} when they write in {lang_name}. Keep your personality but adapt to their language."


_lang_manager = None

def get_lang_manager():
    global _lang_manager
    if _lang_manager is None:
        _lang_manager = LangManager()
    return _lang_manager
